# Building Predictive Model Using Sklearn

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
os.chdir("/Users/sushovanmandal/Documents/code/learn-gen-ai/analyticsVidhya genAI/Foundational ML Algorithams/Module 1 - Regression I/Dataset for the Module")

In [4]:
df = pd.read_csv("Synergix_data_preprocessed.csv")

In [5]:
df = df.drop(columns=['Units_sold>1000'])
df.head()

,Page_traffic,Unit_price,Units_sold,Segment,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,...,Num_of_Promotions,Sum of Spend,Online_Clicks,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline
0,5835.0,22.214389,2071,Skincare,99.0,72.0,194.0,453.0,3272.0,6.0,...,0.0,0.0,1271.0,3102.448115,238075.0,6.0,3479.0,40244.28,3856872.0,2.0
1,1881.0,11.870778,681,Skincare,118.0,73.0,200.0,430.0,3084.0,9.0,...,0.0,0.0,494.0,1723.716359,75868.0,2.0,0.0,0.00,0.0,0.0
2,2477.0,27.645714,875,Makeup,108.0,85.0,232.0,511.0,3402.0,10.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0
3,4087.0,16.896848,1396,Makeup,82.0,64.0,167.0,303.0,2058.0,5.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0
4,1446.0,16.357664,822,Hair Care,29.0,24.0,88.0,200.0,1221.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,6024.0,77040.81,7539723.0,2.0

In [6]:
# One-hot encode the 'Segment' column
df_encoded = pd.get_dummies(df, columns=['Segment'], drop_first=True)
df_encoded['Segment_Makeup'] = df_encoded['Segment_Makeup'].apply(lambda x: 1 if x == True else 0)
df_encoded['Segment_Skincare'] = df_encoded['Segment_Skincare'].apply(lambda x: 1 if x == True else 0)

# Display the first few rows of the modified dataset
df_encoded.head()

,Page_traffic,Unit_price,Units_sold,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,Bullet_Count,...,Online_Clicks,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline,Segment_Makeup,Segment_Skincare
0,5835.0,22.214389,2071,99.0,72.0,194.0,453.0,3272.0,6.0,6.0,...,1271.0,3102.448115,238075.0,6.0,3479.0,40244.28,3856872.0,2.0,0,1
1,1881.0,11.870778,681,118.0,73.0,200.0,430.0,3084.0,9.0,8.0,...,494.0,1723.716359,75868.0,2.0,0.0,0.00,0.0,0.0,0,1
2,2477.0,27.645714,875,108.0,85.0,232.0,511.0,3402.0,10.0,7.0,...,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,1,0
3,4087.0,16.896848,1396,82.0,64.0,167.0,303.0,2058.0,5.0,7.0,...,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,1,0
4,1446.0,16.357664,822,29.0,24.0,88.0,200.0,1221.0,0.0,8.0,...,0.0,0.000000,0.0,0.0,6024.0,77040.81,7539723.0,2.0,0,0

In [7]:
X = df_encoded.drop('Units_sold', axis = 1)
y = df_encoded['Units_sold']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
# Split the data into training and testing sets (80% train, 0% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape

((13741, 25), (5890, 25))

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
# Initialize the Linear Regression model
lr_model = LinearRegression()

In [12]:
# Train the model using the training set
lr_model.fit(X_train, y_train)

LinearRegression()

In [13]:
from sklearn.metrics import r2_score

In [14]:
# Predict target values on the test set
y_train_pred = lr_model.predict(X_train)

# Predict target values on the test set
y_pred = lr_model.predict(X_test)

In [15]:
r2_train = r2_score(y_train, y_train_pred)
print('Train r2 score: ', r2_train)

r2_test = r2_score(y_test, y_pred)
print('Test r2 score: ', r2_test)

Train r2 score:  0.4606909229176207
Test r2 score:  0.46158159201487936

In [16]:
import joblib
filename  = 'Your_model_name.joblib'
joblib.dump(lr_model, filename)
print("Model saved successfully")

Model saved successfully